# Includes complete Jenkins configuration in order to run croc-hunter pipeline
# To install on your own cluster, run:
# helm --namespace jenkins --name jenkins -f ./jenkins-values.yaml install stable/jenkins

Master:
  Memory: "512Mi"

  ServiceType: LoadBalancer
  LoadBalancerSourceRanges:
  - 0.0.0.0/0

  InstallPlugins:
      - kubernetes:0.11           # Kubernetes                         https://plugins.jenkins.io/kubernetes
      - workflow-aggregator:2.5   # Pipeline                           https://plugins.jenkins.io/workflow-aggregator
      - credentials-binding:1.11  # Credentials Binding                https://plugins.jenkins.io/credentials-binding
      - git:3.3.0                 # Git                                https://plugins.jenkins.io/git
      - pipeline-github-lib:1.0   # Pipeline: GitHub Groovy Libraries  https://plugins.jenkins.io/pipeline-github-lib
      - ghprb:1.36.2              # GitHub Pull Request Builder        https://plugins.jenkins.io/ghprb
      - blueocean:1.0.1           # Blue Ocean                         https://plugins.jenkins.io/blueocean

  ScriptApproval:
    - "method groovy.json.JsonSlurperClassic parseText java.lang.String"
    - "new groovy.json.JsonSlurperClassic"
    - "staticMethod org.codehaus.groovy.runtime.DefaultGroovyMethods leftShift java.util.Map java.util.Map"
    - "staticMethod org.codehaus.groovy.runtime.DefaultGroovyMethods split java.lang.String"

Agent:
  Enabled: false
