# Default values for croc-hunter.
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
# name: value

serviceType: LoadBalancer
servicePort: 80
containerPort: 8080
component: "croc-hunter"
replicas: 3
image: "quay.io/etoews/croc-hunter"
imageTag: "latest"
imagePullPolicy: "Always"
cpu: "10m"
memory: "128Mi"
# PodDisruptionBudget
pdb:
  enabled: false
  minAvailable: 2
